# Generated by Django 5.0.1 on 2024-01-11 21:45

import colorfield.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('regular_forms', models.BooleanField(default=False)),
                ('popup_forms', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('background_color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
                ('waveform_height', models.IntegerField(default=10)),
                ('waveform_color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
                ('footer_font_family', models.CharField(default='Times New Roman', max_length=100)),
                ('footer_font_color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
                ('footer_font_size', models.IntegerField(default=10)),
                ('play_pause_button_color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
                ('download_button_color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('page_body_color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NavStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('background_color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
                ('height', models.IntegerField(default=10)),
                ('link_font_family', models.CharField(default='Times New Roman', max_length=100)),
                ('link_font_size', models.IntegerField(default=10)),
                ('link_font_color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
                ('logo_size', models.IntegerField(default=10)),
                ('profile_cart_icon_size', models.IntegerField(default=10)),
                ('is_sticky', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Techno', 'Techno'), ('Hardgroove', 'Hardgroove'), ('Disco', 'Disco'), ('Nu-Disco', 'Nu-Disco'), ('Funk', 'Funk'), ('House', 'House')], default='Genre', max_length=50)),
                ('file', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])])),
                ('album_cover', models.ImageField(default='album_covers/default_cover.jpeg', upload_to='album_covers/')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='date uploaded')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.artist')),
            ],
        ),
    ]
